### ISSUE TITLE
A question on mu_loss

### ISSUE THREAD

**Issue by cyh767** [liuzhen03/ADNet#15]
Hi,

Thanks for the code. I have a question on mu_loss defined here:

[https://github.com/liuzhen03/ADNet/blob/main/graphs/loss/muloss.py#L21](url)

It seems the code uses `norm_perc` to scale the predicted image and ground truth image for tone mapping. But `norm_perc` is obtained from the predicted image. Since the predicted image changes with epochs, the target that the network approximate also changes with epochs. Would it cause the training process less stable? Why not use the ground truth image to get `norm_perc`?

Thank you very much for your answer and help.

**Comment by liuzhen03** [comment]
Hi,

Thanks for your suggestion.

Either using the GT image or the predicted image is ok to get the
`norm_perc'. Actually, it wouldn't hurt the convergence. You can also have
a try by using the GT image to calculate the `norm_perc'.

Best Regards,
Zhen Liu


cyh767 ***@***.***> 于2022年2月22日周二 10:00写道：

**Comment by cyh767** [comment]
I see. Thanks for your reply.
