### ISSUE TITLE
 Can you share NTIRE2021 HDR dataset to me? My email is 18811760578@163.com.

### ISSUE THREAD

**Issue by JinliEmma** [liuzhen03/ADNet#16]

**Comment by liuzhen03** [comment]
Please refer to [the NTIRE2022 HDR Challenge](https://codalab.lisn.upsaclay.fr/competitions/1514) to get the dataset.

**Comment by JinliEmma** [comment]
The training data is only made available to the registered participants. I can not get this dataset from the website.Please share the data.Thanks.
