### ISSUE TITLE
The PSNR-μ on Kalantari et al.'s dataset

### ISSUE THREAD

**Issue by wensongc** [liuzhen03/ADNet#18]
Hi, I trained ADNET on Kalantari et al.'s dataset.  However, after 200 epochs training,  the PSNR-μ is about 43.8, which is lower than your results. Here are some questions:

- I see your answer in[#7](https://github.com/liuzhen03/ADNet/issues/7). Do you keep the gamma correction in  mu-loss on Kalantari et al.'s dataset?

- Also, do I need special data preprocessing process?

Looking forward to your reply！

**Comment by liuzhen03** [comment]
Hi,
1. For Kalantari et al's dataset, the loss is calculated in the tonemapped domain, i.e. by using the \mu-law function instead of the gamma correction. The gamma correction is used for mapping the input LDR images to the HDR domain approximately.
2. Please provide the data preprocessing strategy you are using so that I can better answer your question.

**Comment by wensongc** [comment]
Thanks for your reply！
1. I used the loss calculated in the tonemapping domain. It's same with yours.
2. For the data processing, it's almost same with yours:
- The input LDR images are cropped to 256*256 with stride 128.
- The cropped LDR images are normalized to [0,1], which is dividing by 2**16. 
- Then I used [ ev_alignment() function](https://github.com/liuzhen03/ADNet/blob/e2a68cb58b45fa0b8bae23de6e6a42eacbda6a43/utils/utils.py#L48) in utils.py to process the normalized LDR images.  
   ```
  def ev_alignment(img, expo, gamma):
      return ((img ** gamma) * 2.0**(-1*expo))**(1/gamma)
   ```
   Is that correct? Or am I supposed to use ` (img ** gamma) / expo` here?
- And just like you, I concatenated the above two images together.
- For the label data, I just read them from the .hdr file.

3. By the way, did you use the geometry data augmentation during training, i.e. flipping, rotating.

**Comment by liuzhen03** [comment]
Yes, for Kalantari's dataset, I used `(img ** gamma) / expo'. Please make sure that the crop process is performed offline instead of during your training. I don't use geometry data augmentation, but you can have a try.

**Comment by wensongc** [comment]
I see, I will try it again by using `(img ** gamma) / expo`. Thank you very much 0.0

**Comment by liuzhen03** [comment]
Feel free to reopen it if you have any other questions.
