### ISSUE TITLE
The performance gap between our implementation and your paper report

### ISSUE THREAD

**Issue by ruiliu-ai** [liuzhen03/ADNet#5]
We just trained both ADNet and AHDRNet on NTIRE dataset, the PSNR_l is close to the result of your paper but the PSNR_mu reaches only 34 and 32, respectively. Is this caused by the different choice of validation set? Can you release your validation list?

**Comment by liuzhen03** [comment]
1. This is our settings for validation:
```
# error samples
error_samples = [14, 120, 143, 147, 186, 218, 219, 269, 273, 277, 287, 310, 345, 439, 451, 528, 727, 766, 853, 855, 864, 873, 925, 1026, 1046, 1073, 1077, 1150, 1181, 1294, 1295]
# random samples for validation
val_samples = sorted(random.sample([i for i in range(num_images) if i not in error_samples], 100))
```
we exclude some incomplete samples and randomly select 100 samples for validation.
2. Making sure that you optimize the network in tonemapped domain instead of linear domain. Besides that, the evaluation metric should be the PSNR-\mu.

**Comment by ruiliu-ai** [comment]
What is the definition of 'incomplete' sample? I just checked the samples in your error list but didn't find anything abnormal.

**Comment by liuzhen03** [comment]
The dataset we download during the challenge contains several incomplete samples which lack GT or exposure times. Just ignore it if there is none.
