### ISSUE TITLE
image ranges in mu loss

### ISSUE THREAD

**Issue by viridyu** [liuzhen03/ADNet#7]
Hi, 

Thank you for your sharing, but I am confused about your mu loss calculation. When using your mu loss, both pred and label images have pixel values larger than 1 according to your code. You do gamma correction first, which will lead to the values of hdr_linear_ref and hdr_linear_res much larger. For example, if a pixel in pred image  = 10.0, it will be 174.78 after the gamma correction. Is it reasonable? Why we need to process gamma correction here? Is the gt image in NTIRE dataset in a nonlinear domain? 

I quote your code of mu loss as follows.

```
class mu_loss(object):
    def __init__(self, gamma=2.24, percentile=99):
        self.gamma = gamma
        self.percentile = percentile

    def __call__(self, pred, label):
        hdr_linear_ref = pred ** self.gamma
        hdr_linear_res = label ** self.gamma
...
```

**Comment by liuzhen03** [comment]
Yes, the data range of the NTIRE dataset is [0, N] instead of [0, 1], and N may be very large. Actually, the pixel value distribution is a long-tail.
