### ISSUE TITLE
Could you share your pretrained models of NTIRE and Kalantari?

### ISSUE THREAD

**Issue by UdonDa** [liuzhen03/ADNet#8]
Hi, @liuzhen03 

Could you share your pretrained models of NTIRE and Kalantari?

Best,

**Comment by liuzhen03** [comment]
1. This code repo is released after reorganization, which cannot be directly applied to the original model for the NTIRE competition. 
2. I will release the pre-trained model on Kalantari et al.'s dataset asap.

**Comment by EricMingze** [comment]
hi, thanks for your great work. Are you still considering releasing the pretrained model?
